# Generated by Django 5.2 on 2025-05-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ariza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Ko‘rib chiqilmoqda'), ('accepted', 'Qabul qilingan'), ('rejected', 'Bekor qilingan')], default='pending', max_length=10),
        ),
    ]
