# Generated by Django 5.2 on 2025-05-08 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ariza', '0002_application_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tuman',
                'verbose_name_plural': 'Tumanlar',
            },
        ),
        migrations.CreateModel(
            name='Viloyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Viloyat',
                'verbose_name_plural': 'Viloyatlar',
            },
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Ariza', 'verbose_name_plural': 'Arizalar'},
        ),
        migrations.RemoveField(
            model_name='application',
            name='address',
        ),
        migrations.RemoveField(
            model_name='application',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='selfie_image',
        ),
        migrations.AddField(
            model_name='application',
            name='father_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='selfi_image',
            field=models.ImageField(default=1, upload_to='selfies/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='yashash_joyi',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('in_progress', "Ko'rib chiqilmoqda"), ('accepted', 'Qabul qilingan'), ('rejected', 'Bekor qilingan')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='tuman',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ariza.tuman'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tuman',
            name='viloyat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tumanlar', to='ariza.viloyat'),
        ),
        migrations.AddField(
            model_name='application',
            name='viloyat',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ariza.viloyat'),
            preserve_default=False,
        ),
    ]
