# Generated by Django 5.2 on 2025-05-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ariza', '0003_tuman_viloyat_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', "Ko'rib chiqilmoqda"), ('accepted', 'Qabul qilingan'), ('rejected', 'Bekor qilingan')], default='pending', max_length=20),
        ),
    ]
