# Generated by Django 5.2 on 2025-05-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ariza', '0004_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('in_progress', "Ko'rib chiqilmoqda"), ('accepted', 'Qabul qilingan'), ('rejected', 'Bekor qilingan')], default='new', max_length=20),
        ),
    ]
